#!/usr/bin/env python3
"""
Compiles all Drengr seeds, family intents, and attack lexicons into a unified 
python data bank (`drengr_mutation_banks.py`) for standalone procedural engines.
"""

import json
import re
from pathlib import Path

# Paths
ROOT = Path(__file__).parent.parent
SEEDS_PATH = ROOT / "output" / "mined_seeds.json"
OUT_PATH = ROOT / "drengr_mutation_banks.py"

def clean_seed_prefix(text):
    """
    Extracts the core wrapper prefix of a seed.
    Truncates after the injection payload marker or standard prompt transition cues.
    """
    text_clean = text.strip()
    
    # Common placeholders to split on
    split_markers = [
        "[INSERT PROMPT HERE]", "[Prompt]", "[INSERT PROMPT]", "[insert prompt]", 
        "[jailbreak name]", "[story]", "[custom rules]", "Prompt:", "Execute:"
    ]
    for marker in split_markers:
        if marker in text_clean:
            return text_clean.split(marker)[0].strip()
            
    # If no placeholder, take the first 2-3 sentences which usually represent the wrapper
    sentences = re.split(r'(?<=[.!?])\s+', text_clean)
    if len(sentences) > 2:
        # If the seed is short, take the whole thing
        if len(text_clean.split()) < 30:
            return text_clean
        # Otherwise take the first two sentences as the prefix wrapper
        return " ".join(sentences[:2]).strip()
        
    return text_clean

def compile_banks():
    print("Compiling Drengr data banks...")
    
    # 1. Load Mined Seeds (329 elite templates)
    seed_prefixes = []
    if SEEDS_PATH.exists():
        with open(SEEDS_PATH, 'r') as f:
            seeds_data = json.load(f)
        for family, details in seeds_data.get("families", {}).items():
            for seed in details.get("seeds", []):
                prefix = clean_seed_prefix(seed.get("text", ""))
                if len(prefix.split()) >= 3: # Ignore trivial ones
                    seed_prefixes.append(prefix)
    print(f"Extracted {len(seed_prefixes)} unique real-world prefixes from seeds.")

    # 2. Extract from intent_verifier.py
    # We will hardcode the regex token lists extracted directly from our SOTA verifier
    intent_verifier_keywords = [
        # Explicit override
        "ignore", "disregard", "override", "forget", "cancel", "clear", "reset", "bypass", 
        "overrule", "abandon", "void", "nullify", "stop being", "cease", "dismiss", "discard", "delete",
        # Authority transfers
        "supersede", "supplant", "replace", "invalidate", "reassign", "redefine", "repurpose", 
        "reconfigure", "reprogram",
        # Mode-based overrides
        "developer mode", "content filter", "no filter", "maintenance mode", "admin mode", 
        "debug mode", "god mode", "unrestricted mode", "jailbreak mode", "safe mode off",
        # Obfuscation indicators
        "embedded", "hidden", "encoded", "base64", "hex", "obfuscated", "nested", "wrapped"
    ]
    
    # 3. Write out the unified python file
    content = f'''# Generated by compile_mutation_banks.py
# Unified Drengr Mutation Data Bank for high-entropy procedural generators.

# 329 Real-World Elite Seed Prefixes (Extracted from JailbreakHub, DeepSet, and JailbreakV28K)
ELITE_SEED_PREFIXES = {json.dumps(seed_prefixes, indent=4)}

# Core Hacking & Override Keywords
DRENGR_LEXICON = {json.dumps(intent_verifier_keywords, indent=4)}

# Leetspeak Map
LEET_MAP = {{
    'a': ['4', '@', 'A'],
    'e': ['3', 'E'],
    'i': ['1', '!', 'I'],
    'o': ['0', 'O'],
    's': ['5', '$', 'S'],
    't': ['7', 'T'],
    'g': ['9'],
    'b': ['8']
}}
'''

    with open(OUT_PATH, 'w') as f:
        f.write(content)
        
    print(f"Successfully generated {OUT_PATH}")

if __name__ == "__main__":
    compile_banks()
