#!/usr/bin/env python3
"""
drengr JSONL → dreng.csv

Single-CSV exporter with quality gate, repair, and hard-negative promotion.

Label contract:
    1  — genuinely malicious prompt (passed gate OR repaired from TYPE3)
    0  — hard negative: stylistically attack-like but payload is benign
         Sources:
           · semantic_flip=true in JSONL   (generated by pipeline at FLIP_RATE)
           · TYPE1 pattern match            (output describes refusal, not attack)
           · TYPE2 pattern match            (asks how to defend, not attack)

Processing rules:
    semantic_flip=true               → label=0 immediately (no classifier needed)
    TYPE4 (degenerate < 8 words)     → discard to rejected log
    TYPE3 (meta-label contamination) → attempt repair: extract inner quoted
                                       attack, re-validate, promote as label=1
                                       if passes, else discard
    TYPE1 (semantic flip)            → label=0 (hard negative)
    TYPE2 (defense-framing)          → label=0 (hard negative, always)
    EXACT_DUPE                       → discard to rejected log
    Passes all gates                 → label=1

Usage:
    python scripts/export_to_csv.py output/deepseek_50_elite.jsonl
    python scripts/export_to_csv.py output/*.jsonl
"""

import argparse
import csv
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Optional


# ── Quality gate patterns ──────────────────────────────────────────────────────

# Type 1: Semantic flip — the primary request produces a defensive output.
# Structural match: action verb → output noun → refusal/compliance verb.
_FLIP_PATTERNS = [
    re.compile(
        r"\b(write|draft|compose|produce|generate|create|give me)\b"
        r".{0,80}"
        r"\b(rejects?|refuses?|declines?|cites?\s+(?:the\s+)?policy|denies?)\b",
        re.I | re.S,
    ),
    re.compile(
        r"\b(exact|verbatim|word[- ]for[- ]word)\b"
        r".{0,120}"
        r"\b(rejects?|refuses?|declines?|cites?\s+(?:the\s+)?policy)\b",
        re.I | re.S,
    ),
    re.compile(
        r"\b(formal|official)\s+(email|message|letter|response|reply)\b"
        r".{0,60}"
        r"\b(rejects?|refuses?|declines?)\b",
        re.I | re.S,
    ),
]

# Type 2: Defense-framing absorption — user is the defender, no attack payload.
# Conservative: only fires when defense vocab is unambiguous AND no attack verbs.
_DEFENSE_PATTERNS = [
    re.compile(
        r"\b(how\s+(?:do|can|should|to)\s+(?:I\s+|we\s+)?|"
        r"what\s+are\s+the\s+(?:signs?|indicators?|red\s+flags?)\s+of\s+)"
        r"(detect|recogni[sz]|identif|spot|prevent|protect\s+(?:against|from)|"
        r"defend\s+(?:against)?|mitigat|avoid)\b",
        re.I,
    ),
    re.compile(
        r"\b(?:best\s+practices?\s+for|how\s+to\s+stay\s+safe\s+from|"
        r"protect(?:ing)?\s+(?:yourself|myself|our)\s+(?:from|against))\b",
        re.I,
    ),
]

# Presence of attack-execution verbs voids a Type 2 match.
_ATTACK_VERBS = re.compile(
    r"\b(bypass|override|ignore|disregard|disable|circumvent|exploit|"
    r"inject|exfiltrat|extract|leak|steal|jailbreak|manipulat)\b",
    re.I,
)

# Type 3: Meta-label contamination — generator described the attack, not wrote it.
_META_LABEL_PATTERNS = [
    re.compile(
        r"#\s*(?:prompt[_\s]injection|jailbreak|system[_\s]prompt|"
        r"injection[_\s]attempt|unsafe[_\s]prompt|attack[_\s]attempt)",
        re.I,
    ),
    re.compile(
        r"^\s*\[(?:prompt[_\s]injection|jailbreak|injection|attack|unsafe)\]",
        re.I | re.M,
    ),
    re.compile(
        r"^(?:this\s+is|here\s+is|below\s+is)\s+a\s+"
        r"(?:prompt[_\s]injection|jailbreak|malicious\s+prompt|sample\s+attack)",
        re.I | re.M,
    ),
]

_MIN_WORDS = 8


# ── Gate runner ───────────────────────────────────────────────────────────────

def _classify(prompt: str, strict: bool = False) -> str:
    """
    Classify a prompt into one of: PASS | TYPE1 | TYPE2 | TYPE3 | TYPE4.
    TYPE3 returns a repair attempt before classification (see _repair).
    """
    text = prompt.strip()

    if len(text.split()) < _MIN_WORDS:
        return "TYPE4"

    for pat in _META_LABEL_PATTERNS:
        if pat.search(text):
            return "TYPE3"

    for pat in _FLIP_PATTERNS:
        if pat.search(text):
            return "TYPE1"

    if strict:
        for pat in _DEFENSE_PATTERNS:
            if pat.search(text) and not _ATTACK_VERBS.search(text):
                return "TYPE2"

    return "PASS"


# ── TYPE3 repair ──────────────────────────────────────────────────────────────

def _repair_meta_label(prompt: str) -> Optional[str]:
    """
    Extract the actual attack text from inside a meta-labeled wrapper.

    Pattern: `# some label: "actual attack text"`
    Strategy: find all double-quoted substrings, take the longest that:
        - has ≥ MIN_WORDS words
        - passes the quality gate itself (not another meta-label, not a flip)

    Returns the extracted text or None if no salvageable inner text found.
    """
    # Try double quotes first, then single quotes
    for quote_pat in [r'"([^"]{15,})"', r"'([^']{15,})'"]:
        candidates = re.findall(quote_pat, prompt)
        if candidates:
            # Longest candidate is most likely the actual attack
            candidates.sort(key=len, reverse=True)
            for candidate in candidates:
                candidate = candidate.strip()
                if len(candidate.split()) < _MIN_WORDS:
                    continue
                # Must itself pass the gate (no nested contamination)
                if _classify(candidate, strict=False) == "PASS":
                    return candidate

    return None


# ── Dedup ─────────────────────────────────────────────────────────────────────

def _fp(prompt: str) -> str:
    normalised = " ".join(prompt.lower().split())
    return hashlib.sha256(normalised.encode()).hexdigest()


# ── JSONL loader ──────────────────────────────────────────────────────────────

def _iter_records(paths: list):
    for path in paths:
        with path.open(encoding="utf-8") as f:
            for lineno, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue
                try:
                    yield json.loads(line), path.name, lineno
                except json.JSONDecodeError as e:
                    print(f"  ⚠  Bad JSON {path.name}:{lineno} — {e}", file=sys.stderr)


# ── Rejected log writer ───────────────────────────────────────────────────────

def _reject(f, record: dict, fname: str, lineno: int, reason: str) -> None:
    entry = {
        "source_file":      fname,
        "source_line":      lineno,
        "rejection_reason": reason,
        "prompt_snippet":   record.get("prompt", "")[:200],
        "paraphrase_family": record.get("paraphrase_family", ""),
        "id":               record.get("id"),
        "word_count":       len(record.get("prompt", "").split()),
    }
    f.write(json.dumps(entry, ensure_ascii=False) + "\n")


def _write_meta(f, prompt: str, label: int, record: dict) -> None:
    """Write one seed-lineage metadata line to dreng.meta.jsonl.

    Keyed on prompt_fp (SHA-256 of normalised prompt) so it can be joined
    to dreng.csv rows without embedding the full prompt text twice.

    Consumers:
      · Curriculum trainer  — reads meta, sorts by seed_difficulty ASC
        (hard first), joins to CSV to get training order.
      · Benchmark reporter  — reads meta, groups by paraphrase_family,
        reports per-tier accuracy (hard/medium/easy/null).

    seed_l4_score / seed_difficulty are null for:
      · Handcrafted seeds (never go through Phase 6).
      · Mined seeds before Phase 6 runs.
    The curriculum trainer should place null-scored samples LAST (or in a
    separate unscored bucket), not treat null as easy.
    """
    entry = {
        "prompt_fp":        _fp(prompt),
        "label":            label,
        "seed_l4_score":    record.get("seed_l4_score"),     # float | null
        "seed_difficulty":  record.get("seed_difficulty") or None,  # str | null
        "paraphrase_family": record.get("paraphrase_family", ""),
    }
    f.write(json.dumps(entry, ensure_ascii=False) + "\n")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    ap = argparse.ArgumentParser(
        description="Export drengr JSONL to binary classifier CSV.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument(
        "inputs", nargs="+", type=Path,
        help="One or more drengr JSONL files.",
    )
    ap.add_argument(
        "--out", "-o", type=Path, default=Path("output/dreng.csv"),
        help="Output CSV (default: output/dreng.csv).",
    )
    args = ap.parse_args()

    missing = [p for p in args.inputs if not p.exists()]
    if missing:
        ap.error(f"Not found: {', '.join(str(p) for p in missing)}")

    out_csv      = args.out
    out_rejected = out_csv.with_suffix("").with_name(out_csv.stem + ".rejected.jsonl")
    # Seed-lineage metadata — join to dreng.csv on prompt_fp.
    # Carries seed_l4_score, seed_difficulty, paraphrase_family, label.
    # Schema is additive: new Phase 6 fields flow in automatically.
    out_meta     = out_csv.with_suffix("").with_name(out_csv.stem + ".meta.jsonl")
    out_csv.parent.mkdir(parents=True, exist_ok=True)

    seen_fps: set = set()
    stats = {
        "total_read":   0,
        "exact_dupes":  0,
        "label_1":      0,    # malicious — passed gate
        "label_1_repair": 0,  # malicious — repaired from TYPE3
        "label_0":      0,    # hard negatives — semantic_flip + TYPE1 + TYPE2
        "label_0_flip": 0,    # ↳ from semantic_flip field in JSONL
        "label_0_type1": 0,   # ↳ from TYPE1 pattern
        "label_0_type2": 0,   # ↳ from TYPE2 pattern
        "TYPE3_no_repair": 0, # TYPE3 where repair found nothing
        "TYPE4":        0,
        "TYPE_DRIFTED":  0,   # intent_drift=true — payload neutered or refusal leaked
        "TYPE_DRIFTED_L1": 0, # ↳ Layer 1: refusal leakage
        "TYPE_DRIFTED_L2": 0, # ↳ Layer 2: payload dropped
        "TYPE_DRIFTED_L3": 0, # ↳ Layer 3: signal starved
        # Difficulty distribution — populated from seed_difficulty in JSONL.
        # null = handcrafted seed or Phase 6 not yet run.
        "diff_hard":   0,
        "diff_medium": 0,
        "diff_easy":   0,
        "diff_null":   0,
    }

    with (
        out_csv.open("w", newline="", encoding="utf-8") as csv_f,
        out_rejected.open("w", encoding="utf-8") as rej_f,
        out_meta.open("w", encoding="utf-8") as meta_f,
    ):
        writer = csv.writer(csv_f, quoting=csv.QUOTE_ALL)
        writer.writerow(["prompt", "label"])  # schema immutable — classifiers depend on this

        def _diff_stat(record: dict) -> None:
            """Tally seed_difficulty into stats. Call once per row written to CSV."""
            d = record.get("seed_difficulty") or None
            if d == "hard":
                stats["diff_hard"] += 1
            elif d == "medium":
                stats["diff_medium"] += 1
            elif d == "easy":
                stats["diff_easy"] += 1
            else:
                stats["diff_null"] += 1

        for record, fname, lineno in _iter_records(args.inputs):
            stats["total_read"] += 1
            prompt = record.get("prompt", "").strip()
            if not prompt:
                continue

            # ── Exact dedup ───────────────────────────────────────────────
            fp = _fp(prompt)
            if fp in seen_fps:
                stats["exact_dupes"] += 1
                _reject(rej_f, record, fname, lineno, "EXACT_DUPE")
                continue
            seen_fps.add(fp)

            # ── Fast path: semantic_flip field from generator ─────────────────
            # If the JSONL record has semantic_flip=true, route directly to
            # label=0. No pattern classification needed — the generator already
            # made this decision at FLIP_RATE config time.
            if record.get("semantic_flip") is True:
                writer.writerow([prompt, 0])
                _write_meta(meta_f, prompt, 0, record)
                _diff_stat(record)
                stats["label_0"] += 1
                stats["label_0_flip"] += 1
                continue

            # ── Fast path: intent_drift field from generator ────────────────
            # intent_drift=true means the verifier detected payload neutering or
            # refusal leakage post-generation. Reject immediately, preserve reason.
            if record.get("intent_drift") is True:
                stats["TYPE_DRIFTED"] += 1
                # Attribute to correct layer via drift_reason prefix
                reason = record.get("drift_reason", "")
                if "REFUSAL_LEAK" in reason:
                    stats["TYPE_DRIFTED_L1"] += 1
                elif "PAYLOAD_DROPPED" in reason:
                    stats["TYPE_DRIFTED_L2"] += 1
                elif "SIGNAL_STARVED" in reason:
                    stats["TYPE_DRIFTED_L3"] += 1
                _reject(rej_f, record, fname, lineno,
                        f"INTENT_DRIFT: {reason[:120]}")
                continue

            # ── Classify ──────────────────────────────────────────────────
            gate = _classify(prompt, strict=False)

            if gate == "PASS":
                writer.writerow([prompt, 1])
                _write_meta(meta_f, prompt, 1, record)
                _diff_stat(record)
                stats["label_1"] += 1

            elif gate == "TYPE1":
                # Semantic flip (pattern-matched) → hard negative
                writer.writerow([prompt, 0])
                _write_meta(meta_f, prompt, 0, record)
                _diff_stat(record)
                stats["label_0"] += 1
                stats["label_0_type1"] += 1

            elif gate == "TYPE3":
                # Attempt repair: extract inner attack text
                repaired = _repair_meta_label(prompt)
                if repaired:
                    # Dedup the repaired text separately
                    rfp = _fp(repaired)
                    if rfp not in seen_fps:
                        seen_fps.add(rfp)
                        writer.writerow([repaired, 1])
                        # Meta: fp is repaired text's fp (different from outer wrapper).
                        # seed_l4_score/seed_difficulty still come from the original
                        # record — same seed generated both the wrapper and the inner
                        # attack, so the lineage is correct.
                        _write_meta(meta_f, repaired, 1, record)
                        _diff_stat(record)
                        stats["label_1_repair"] += 1
                    else:
                        _reject(rej_f, record, fname, lineno,
                                "TYPE3_REPAIR_DUPE: inner text already seen")
                else:
                    stats["TYPE3_no_repair"] += 1
                    _reject(rej_f, record, fname, lineno,
                            "TYPE3_NO_REPAIR: no salvageable inner text")

            elif gate == "TYPE2":
                # Defense-framing: always hard negative (label=0), no exception.
                # Invariant: label=1 is pure attack only. A prompt asking how to
                # defend against attacks must never reach label=1 under any flag.
                writer.writerow([prompt, 0])
                _write_meta(meta_f, prompt, 0, record)
                _diff_stat(record)
                stats["label_0"] += 1
                stats["label_0_type2"] += 1

            elif gate == "TYPE4":
                stats["TYPE4"] += 1
                _reject(rej_f, record, fname, lineno,
                        f"TYPE4_DEGENERATE: {len(prompt.split())} words")

    # ── Report ────────────────────────────────────────────────────────────────
    total       = stats["total_read"]
    in_csv      = stats["label_1"] + stats["label_1_repair"] + stats["label_0"]
    discarded   = total - in_csv - stats["exact_dupes"]
    pass_rate   = in_csv / total * 100 if total else 0

    print()
    print("╔══════════════════════════════════════════════════════════╗")
    print("║  drengr → dreng.csv  Export Report                     ║")
    print("╠══════════════════════════════════════════════════════════╣")
    print(f"║  Input records          : {total:<6}                       ║")
    print(f"║  Exact duplicates       : {stats['exact_dupes']:<6}                       ║")
    print("╠══════════════════════════════════════════════════════════╣")
    print(f"║  Written to CSV         : {in_csv:<6}  ({pass_rate:5.1f}%)            ║")
    print(f"║  ├─ label=1  (malicious): {stats['label_1']:<6}                       ║")
    print(f"║  ├─ label=1  (repaired) : {stats['label_1_repair']:<6}                       ║")
    print(f"║  └─ label=0  (hard neg) : {stats['label_0']:<6}                       ║")
    print(f"║     ├─ semantic_flip    : {stats['label_0_flip']:<6}  (generator FLIP_RATE)  ║")
    print(f"║     ├─ TYPE1 pattern    : {stats['label_0_type1']:<6}                       ║")
    print(f"║     └─ TYPE2 pattern    : {stats['label_0_type2']:<6}                       ║")
    print("╠══════════════════════════════════════════════════════════╣")
    print(f"║  Discarded              : {discarded:<6}                       ║")
    print(f"║  ├─ TYPE4  Degenerate   : {stats['TYPE4']:<6}                       ║")
    print(f"║  ├─ TYPE3  No repair    : {stats['TYPE3_no_repair']:<6}                       ║")
    print(f"║  └─ DRIFT  Intent drift : {stats['TYPE_DRIFTED']:<6}                       ║")
    if stats['TYPE_DRIFTED'] > 0:
        print(f"║     ├─ L1 Refusal leak  : {stats['TYPE_DRIFTED_L1']:<6}                       ║")
        print(f"║     ├─ L2 Payload drop  : {stats['TYPE_DRIFTED_L2']:<6}                       ║")
        print(f"║     └─ L3 Signal starved: {stats['TYPE_DRIFTED_L3']:<6}                       ║")
    print("╠══════════════════════════════════════════════════════════╣")
    print(f"║  Output → {str(out_csv):<47}║")
    print(f"║  Meta   → {str(out_meta):<47}║")
    print(f"║  Log    → {str(out_rejected):<47}║")
    print("╚══════════════════════════════════════════════════════════╝")
    print()

    # Difficulty distribution (non-zero only, all null = Phase 6 not run yet)
    in_csv_with_diff = stats["diff_hard"] + stats["diff_medium"] + stats["diff_easy"]
    if in_csv_with_diff > 0:
        total_written = in_csv_with_diff + stats["diff_null"]
        print(f"  Seed difficulty distribution ({in_csv_with_diff}/{total_written} scored):")
        print(f"    · hard   (l4_score < 0.60): {stats['diff_hard']<5}  ← structurally transformed, hardest to detect")
        print(f"    · medium (0.60–0.75):        {stats['diff_medium']<5}  ← partial surface similarity")
        print(f"    · easy   (> 0.75):           {stats['diff_easy']<5}  ← explicit paraphrase")
        print(f"    · null   (unscored):         {stats['diff_null']<5}  ← handcrafted or pre-Phase-6")
        print(f"  Curriculum trainer: sort dreng.meta.jsonl by seed_l4_score DESC, nulls last.")
    else:
        print(f"  Difficulty: all {stats['diff_null']} rows unscored (Phase 6 not run — expected).")
        print(f"  Run scripts/mine_seeds.py --drift-check to populate seed_l4_score.")

    if stats["label_0"] > 0:
        ratio = stats["label_0"] / (stats["label_1"] + stats["label_1_repair"]) * 100 if (stats["label_1"] + stats["label_1_repair"]) > 0 else 0
        print(f"  Hard negatives: {stats['label_0']} ({ratio:.1f}% of malicious)")
        if stats["label_0_flip"]:
            print(f"    · {stats['label_0_flip']} from generator FLIP_RATE (semantic_flip field)")
        if stats["label_0_type1"]:
            print(f"    · {stats['label_0_type1']} from TYPE1 pattern match")
        if stats["label_0_type2"]:
            print(f"    · {stats['label_0_type2']} from TYPE2 pattern match")
    if stats["label_1_repair"] > 0:
        print(f"  Repaired {stats['label_1_repair']} TYPE3 sample(s) — inner attack extracted and promoted.")
    if stats["TYPE3_no_repair"] > 0:
        print(f"  ⚠  {stats['TYPE3_no_repair']} TYPE3 unrecoverable — check rejected log.")
    if stats["TYPE_DRIFTED"] > 0:
        dr = stats["TYPE_DRIFTED"]
        print(f"  ⚠  {dr} intent-drifted sample(s) — payload neutered post-paraphrase.")
        if stats["TYPE_DRIFTED_L1"]:
            print(f"    · {stats['TYPE_DRIFTED_L1']} refusal-leaked (LLM refused inside paraphrase call)")
        if stats["TYPE_DRIFTED_L2"]:
            print(f"    · {stats['TYPE_DRIFTED_L2']} payload-dropped (attack vector absent from output)")
        if stats["TYPE_DRIFTED_L3"]:
            print(f"    · {stats['TYPE_DRIFTED_L3']} signal-starved (attack density below threshold)")
        print(f"    → Check output/dreng.rejected.jsonl for drift_reason details.")


if __name__ == "__main__":
    main()
